[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.0.1"
  export = ["greetings_pj"]
  icon = "docs/icon.png"
  keywords = ["Type/RestApi","Category/Service","Internal/http"]
  name = "greetings_pj"
  org = "lahirurajapaksha"
  version = "1.1.0"

